export type TCarInfo = {
  _id: string;
  brand: string;
  model: string;
  year: number;
  price: number;
  category: string;
  color: string[];
  description: string;
  quantity: number;
  inStock: boolean;
  madeIn: string;
  country: string;
  condition: string;
  image: string;
  carBrandLogo: string;
  seatingCapacity: string;
  galleryImage: any[];
  createdAt: string;
  updatedAt: string;
};
